version: 2.1

orbs:
  python: circleci/python@0.3.2
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: '3.7'
    steps:
      - checkout
      - run:
          name: Setup Virtual env
          command: |
            virtualenv -p python3.7 env
            echo "source ./env/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test:
          context: serverless-fastapi-dev
          filters:
            branches:
              only:
                - cicd-test-1